services:
  postgres:
    image: docker.io/library/postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "trustify"
      POSTGRES_DB: "trustify"
    restart: always
    shm_size: '1g'
    command: >
      postgres -c random_page_cost=1.1 -c max_parallel_workers_per_gather=4 -c shared_preload_libraries='pg_stat_statements'
