receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
  debug:
    verbosity: basic
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch: {}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
