[package]
name = "trustify-common"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[features]
ai = [ "trustify-migration/ai" ]

[dependencies]
trustify-migration = { workspace = true }

actix-web = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
cpe = { workspace = true }
deepsize = { workspace = true }
hex = { workspace = true }
hide = { workspace = true }
human-date-parser = { workspace = true }
itertools = { workspace = true }
lenient_semver = { workspace = true }
log = { workspace = true }
native-tls = { workspace = true }
packageurl = { workspace = true }
pem = { workspace = true }
percent-encoding = { workspace = true }
postgresql_embedded = { workspace = true, features = ["blocking", "tokio"] }
regex = { workspace = true }
reqwest = { workspace = true, features = ["native-tls"] }
ring = { workspace = true }
sbom-walker = { workspace = true }
schemars = { workspace = true }
sea-orm = { workspace = true, features = ["sea-query-binder", "sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sea-query = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
spdx-expression = { workspace = true }
spdx-rs = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
utoipa = { workspace = true, features = ["url"] }
uuid = { workspace = true, features = ["v5", "serde"] }
walker-common = { workspace = true, features = ["bzip2", "liblzma", "flate2"]}
humantime = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
test-context = { workspace = true }
test-log = { workspace = true, features = ["log", "trace"] }
time = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["full"] }

trustify-test-context = { workspace = true }
